INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (1, 'ریاضی گرایش کاربردی', '111109', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (2, 'ریاضی کاربردی', '111118', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (3, 'ریاضی محض گرایش جبر', '111119', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (4, 'ریاضی (محض )', '111120', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (5, 'ریاضی کاربردی گرایش بهینه سازی (تحقیق در عملیات)', '111121', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (6, 'ریاضی محض گرایش هندسه (توپولوژی)', '111122', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (7, 'ریاضی کاربردی گرایش بهینه سازی', '111123', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (8, 'ریاضی گرایش هندسه توپولوژی', '111124', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (9, 'ریاضی (کاربردی )', '111130', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (10, 'آموزش ریاضی', '111131', 7, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (11, 'ریاضیات و کاربردها', '111132', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (12, 'ریاضی محض- زمینه گراف و ترکیبات جبری', '111148', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (13, 'آموزش ریاضی', '111149', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (14, 'ریاضی کاربردی- آنالیزعددی', '111150', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (15, 'ریاضی محض (آنالیز)', '111160', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (16, 'ریاضی محض (جبر)', '111170', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (17, 'ریاضی محض (هندسه )', '111180', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (18, 'ریاضی کاربردی گرایش تحقیق در عملیات', '111181', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (19, 'ریاضی کاربردی (تحقیق درعملیات )', '111190', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (20, 'ریاضی محض -آنالیز', '111191', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (21, 'ریاضی کاربردی- تحقیق درعملیات(کنترل وبهینه سازی)', '111196', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (22, 'ریاضی محض -هندسه', '111197', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (23, 'ریاضی محض -جبر جابجایی وهمولوژی', '111198', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (24, 'ریاضی محض- ابر جبرها وجبرهای مرتب شده', '111199', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (25, 'بیو شیمی', '111207', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (26, 'زیست شناسی-فیزیولوژی گیاهی', '111208', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (27, 'بیوشیمی', '111209', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (28, 'زیست شناسی گرایش عمومی', '111210', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (29, 'زیست شناسی گیاهی', '111211', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (30, 'زیست شناسی سلولی و مولکولی', '111212', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (31, 'زیست شناسی (دبیری )', '111220', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (32, 'زیست شناسی - علوم جانوری گرایش بافت شناسی و جنین شناسی', '111221', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (33, 'زیست فناوری گرایش میکروبی', '111222', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (34, 'علوم جانوری گرایش فیزیولوژی', '111223', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (35, 'علوم جانوری گرایش بیوسیستماتیک', '111224', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (36, 'علوم گیاهی گرایش فیزیولوژی', '111225', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (37, 'علوم گیاهی گرایش سیستماتیک و بوم شناسی', '111226', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (38, 'علوم گیاهی گرایش زیست شناسی سلولی و تکوینی', '111227', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (39, 'ژنتیک', '111228', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (40, 'علوم جانوری گرایش زیست شناسی سلولی و تکوینی', '111229', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (41, 'زیست شناسی', '111230', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (42, 'بیوفیزیک', '111237', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (43, 'زیست شناسی-بیوفیزیک', '111238', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (44, 'زیست شناسی گرایش علوم گیاهی', '111240', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (45, 'آموزش علوم تجربی', '111241', 7, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (46, 'زیست شناسی-ژنتیک', '111242', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (47, 'علوم جانوری گرایش فیزیولوژی جانوری', '111243', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (48, 'علوم جانوری گرایش بیوسیستماتیک جانوری', '111244', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (49, 'زیست شناسی- علوم جانوری گرایش زیست شناسی سلولی تکوینی', '111245', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (50, 'علوم گیاهی گرایش زیست شناسی تکوینی', '111246', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (51, 'علوم گیاهی گرایش سیستماتیک اکولوژی', '111247', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (52, 'علوم گیاهی گرایش فیزیولوژی گیاهی', '111248', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (53, 'زیست فناوری(بیوتکنولوژی) گرایش میکروبی', '111249', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (54, 'زیست شناسی (علوم گیاهی )', '111250', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (55, 'زیست شناسی سلولی و مولکولی گرایش بیوفیزیک', '111251', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (56, 'زیست شناسی گیاهی گرایش فیزیولوژی', '111252', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (57, 'زیست شناسی گیاهی گرایش سیستماتیک و بوم شناسی', '111253', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (58, 'زیست شناسی گیاهی گرایش زیست شناسی سلولی و تکوینی', '111254', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (59, 'زیست شناسی جانوری گرایش زیست شناسی سلولی و تکوینی', '111255', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (60, 'زیست شناسی جانوری گرایش بیوسیستماتیک', '111256', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (61, 'زیست شناسی جانوری گرایش فیزیولوژی', '111257', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (62, 'زیست شناسی سلولی و مولکولی گرایش بیوشیمی', '111258', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (63, 'زیست شناسی سلولی و مولکولی گرایش ژنتیک', '111259', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (64, 'زیست شناسی (علوم جانوری )', '111260', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (65, 'زیست شناسی (بیوشیمی )', '111270', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (66, 'زیست شناسی گیاهی گرایش سلولی و تکوینی', '111274', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (67, 'زیست شناسی جانوری گرایش سلولی و تکوینی', '111275', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (68, 'فیزیک-فیزیک نظری', '111308', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (69, 'فیز یک', '111309', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (70, 'فیزیک (کاربردی )', '111310', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (71, 'فیزیک- ماده چگال', '111311', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (72, 'فیزیک- هواشناسی', '111312', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (73, 'ذرات بنیادی- کیهان شناسی- اختر فیزیک', '111313', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (74, 'فیزیک (هسته ای )', '111320', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (75, 'فیزیک گرایش هسته ای', '111324', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (76, 'فیزیک گرایش فیزیک بنیادی', '111325', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (77, 'فیزیک گرایش اتمی و مولکولی', '111326', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (78, 'فیزیک گرایش ذرات بنیادی و نظریه میدان ها', '111328', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (79, 'فیزیک گرایش فیزیک نجومی', '111329', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (80, 'فیزیک', '111331', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (81, 'فیزیک (زمینه حالت جامد)', '111332', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (82, 'فیزیک (زمینه ذرات بنیادی )', '111333', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (83, 'فیزیک (زمینه گرانش وفیزیک نجومی )', '111334', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (84, 'فیزیک (زمینه هسته ای )', '111335', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (85, 'فیزیک (زمینه اتمی ومولکولی )', '111336', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (86, 'فیزیک (اتمی و مولکولی)', '111337', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (87, 'فیزیک (حالت جامد)', '111338', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (88, 'فیزیک(زمینه فیزیک بنیادی)', '111339', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (89, 'فیزیک گرایش حالت جامد', '111343', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (90, 'فیزیک گرایش هسته ای', '111345', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (91, 'فیزیک گرایش اپتیک و لیزر', '111346', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (92, 'فیزیک گرایش فیزیک پلاسما', '111348', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (93, 'فیزیک گرایش فیزیک ماده چگال', '111349', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (94, 'فیزیک گرایش گرانش و کیهان شناسی', '111350', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (95, 'فیزیک گرایش نجوم و اختر فیزیک', '111351', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (96, 'فیزیک گرایش فیزیک هسته ای', '111353', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (97, 'فیتوشیمی', '111411', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (98, 'شیمی گرایش محض', '111420', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (99, 'شیمی (کاربردی )', '111440', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (100, 'شیمی (شیمی تجزیه )', '111460', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (101, 'شیمی (شیمی آلی )', '111470', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (102, 'شیمی (شیمی فیزیک )', '111480', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (103, 'شیمی (شیمی معدنی )', '111490', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (104, 'شیمی-شیمی فیزیک', '111494', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (105, 'شیمی -شیمی تجزیه', '111495', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (106, 'شیمی -شیمی آلی', '111496', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (107, 'شیمی-شیمی معدنی', '111497', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (108, 'مهندسی کامپیوتر(نرم افزار)', '111510', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (109, 'مهندسی فناوری اطلاعات', '111512', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (110, 'مهندسی کامپیوتر-نرم افزار', '111513', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (111, 'زمین شناسی (محض )', '111610', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (112, 'زمین شناسی', '111611', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (113, 'زمین شیمی', '111612', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (114, 'آب زمین شناسی', '111613', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (115, 'زلزله شناسی', '111614', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (116, 'زمین شناسی (دبیری )', '111620', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (117, 'علوم زمین گرایش پترولوژی', '111631', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (118, 'علوم زمین گرایش زمین شناسی زیست محیطی', '111632', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (119, 'علوم زمین گرایش زمین شناسی اقتصادی', '111633', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (120, 'علوم زمین گرایش زمین ساخت (تکتونیک)', '111634', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (121, 'علوم زمین گرایش آب زمین شناسی', '111635', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (122, 'علوم زمین گرایش چینه نگاری و دیرینه شناسی', '111636', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (123, 'علوم زمین گرایش رسوب شناسی و سنگ شناسی رسوبی', '111637', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (124, 'علوم زمین گرایش زمین شیمی', '111638', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (125, 'زمین شناسی (کاربردی )', '111640', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (126, 'زمین شناسی (چینه شناسی وفسیل شناسی )', '111641', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (127, 'زمین شناسی- پترولوژی', '111642', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (128, 'زمین شناسی (اقتصادی )', '111643', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (129, 'زمین شناسی-آبشناسی', '111646', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (130, 'زمین شناسی-رسوب شناسی وسنگ شناسی رسوبی', '111647', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (131, 'زمین شناسی زیست محیطی', '111648', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (132, 'زمین ساخت(تکتونیک)', '111650', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (133, 'چینه نگاری و دیرینه شناسی', '111651', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (134, 'رسوب شناسی و سنگ شناسی رسوبی', '111652', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (135, 'آما ر', '111709', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (136, 'آمار', '111710', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (137, 'آمارریاضی', '111711', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (138, 'آمار و کاربردها', '111713', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (139, 'آمار گرایش آمار ریاضی', '111714', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (140, 'بهداشت محیط', '111810', 6, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (141, 'علوم کامپیوتر', '111910', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (142, 'علوم کامپیوترکاردانی', '111911', 6, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (143, 'مهندسی معماری', '112010', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (144, 'مهندسی کشاورزی (اقتصادکشاورزی)', '112110', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (145, 'مهندسی صنایع', '112211', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (146, 'مهندسی صنایع -صنایع', '112212', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (147, 'مهندسی صنایع', '112214', 10, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (148, 'مهندسی صنا یع', '112215', 8, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (149, 'ژئوفیزیک-شاخه زلزله شناسی', '112410', 9, 1);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (150, 'آموزش و پرورش کودکان با نیازهای ویژه', '121101', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (151, 'تکنولوژی آموزشی', '121102', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (152, 'علوم تربیتی گرایش آموزش و پرورش پیش دبستانی و دبستانی', '121110', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (153, 'فلسفه تعلیم وتربیت- تعلیم وتربیت اسلامی', '121112', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (154, 'مشاوره و راهنمایی', '121113', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (155, 'مشاوره گرایش مشاوره خانواده', '121114', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (156, 'برنامه ریزی درسی', '121116', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (157, 'تکنولوژی آموزشی', '121117', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (158, 'مشاوره گرایش مشاوره مدرسه', '121118', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (159, 'مشاوره گرایش مشاوره شغلی', '121119', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (160, 'علوم تربیتی گرایش مدیریت و برنامه ریزی آموزشی', '121120', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (161, 'مشاوره گرایش مشاوره توانبخشی', '121121', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (162, 'علوم تربیتی', '121130', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (163, 'آموزش و پرورش ابتدایی', '121142', 7, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (164, 'آموزش وبهسازی منابع انسانی', '121149', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (165, 'علوم تربیتی (برنامه ریزی درسی )', '121150', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (166, 'علوم تربیتی- برنامه ریزی آموزشی', '121160', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (167, 'تاریخ وفلسفه آموزش وپرورش گرایش تعلیم وتربیت اسلامی', '121161', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (168, 'تحقیقات آموزشی', '121162', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (169, 'برنامه ریزی آموزش ازراه دور', '121165', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (170, 'علوم تربیتی گرایش آموزش و پرورش پیش دبستانی ودبستانی', '121171', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (171, 'علوم تربیتی گرایش مدیریت و برنامه ریزی آموزشی', '121172', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (172, 'راهنمایی و مشاوره', '121173', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (173, 'مدیریت آموزشی', '121174', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (174, 'آموزش حرفه و فن', '121176', 7, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (175, 'امور تربیتی', '121177', 7, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (176, 'مترجمی زبان انگلیسی', '121210', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (177, 'آموزش زبان فارسی به غیرفارسی زبانان', '121211', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (178, 'مترجمی زبان انگلیسی', '121212', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (179, 'زبان و ادبیات انگلیسی', '121229', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (180, 'زبان شناسی همگانی', '121230', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (181, 'زبان شناسی همگانی', '121231', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (182, 'مترجمی زبان انگلیسی (کاردانی )', '121232', 6, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (183, 'زبان و ادبیات فارسی گرایش ویرایش و نگارش', '121311', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (184, 'زبان و ادبیات فارسی', '121320', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (185, 'زبان و ادبیات فارسی', '121340', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (186, 'زبان وادبیات فارسی گرایش ادبیات مقاومت', '121341', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (187, 'زبان وادبیات فارسی -ادبیات کودک ونوجوان', '121342', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (188, 'زبان وادبیات فارسی-ادبیات پایداری', '121343', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (189, 'زبان و ادبیات فارسی گرایش ادبیات تطبیقی (فارسی - عربی)', '121344', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (190, 'زبان و ادبیات فارسی گرایش ادبیات عامه', '121345', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (191, 'زبان و ادبیات فارسی گرایش ادبیات تطبیقی', '121346', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (192, 'زبان و ادبیات فارسی گرایش آموزش زبان فارسی', '121347', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (193, 'زبان و ادبیات فارسی', '121350', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (194, 'آموزش زبان فارسی', '121351', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (195, 'حسابداری', '121410', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (196, 'حسابداری (کاردانی )', '121411', 6, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (197, 'حسا بداری', '121412', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (198, 'حسابدار ی', '121413', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (199, 'حسابرسی', '121414', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (200, 'تربیت بدنی وعلوم ورزشی- دبیری', '121510', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (201, 'رفتارحرکتی-رشدحرکتی', '121511', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (202, 'علوم ورزشی', '121515', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (203, 'تربیت بدنی و علوم ورزشی', '121520', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (204, 'تربیت بدنی و علوم ورزشی', '121521', 7, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (205, 'مدیریت ورزشی-مدیریت بازاریابی در ورزش', '121522', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (206, 'مدیریت ورزشی-مدیریت اماکن وتاسیسات ورزشی', '121523', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (207, 'مدیریت ورزشی-مدیریت اوقات فراغت ورزشهای تفریحی', '121524', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (208, 'مدیریت ورزشی-مدیریت راهبردی در سازمانهای ورزشی', '121525', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (209, 'مدیریت ورزشی-مدیریت رویدادهای ورزشی', '121526', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (210, 'آسیب شناسی ورزشی وحرکات اصلاحی-حرکات اصلاحی', '121527', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (211, 'فیزیولوژی ورزشی-فیزیولوژی ورزشی کاربردی', '121528', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (212, 'فیزیولوژی ورزشی-فیزیولوژی فعالیت بدنی وتندرستی', '121529', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (213, 'تربیت بدنی وعلوم ورزشی', '121530', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (214, 'تربیت بدنی (مدیریت وبرنامه ریزی )', '121531', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (215, 'تربیت بدنی وعلوم ورزشی (خواهران )', '121532', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (216, 'تربیت بدنی وعلوم ورزشی (برادران )', '121533', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (217, 'تربیت بدنی وعلوم ورزشی (مدیریت و برنامه ریزی تربیت بدنی)(کاردانی )', '121534', 6, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (218, 'تربیت بدنی وعلوم ورزشی گرایش عمومی', '121535', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (219, 'تربیت بدنی وعلوم ورزشی (فیزیولوژی ورزش)', '121536', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (220, 'تربیت بدنی وعلوم ورزشی (مدیریت ورزشی )', '121537', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (221, 'تربیت بدنی وعلوم ورزشی (حرکات اصلاحی وآسیب شناسی)', '121538', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (222, 'مدیریت ورزشی-مدیریت رسانه های ورزشی', '121539', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (223, 'علوم ورزشی گرایش علوم زیستی ورزش', '121540', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (224, 'علوم ورزشی گرایش علوم انسانی ورزش', '121541', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (225, 'جغرافیای انسانی (روستایی )', '121610', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (226, 'مخاطرات محیطی گرایش طبیعی', '121615', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (227, 'جغرافیا', '121617', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (228, 'جغرافیا سیاسی گرایش فضای شهری', '121619', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (229, 'جغرافیاوبرنامه ریزی روستایی', '121620', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (230, 'جغرافیاوبرنامه ریزی روستایی', '121620', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (231, 'برنامه ریزی آمایش سرزمین', '121621', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (232, 'جغرافیا و برنامه ریزی روستایی گرایش توسعه اقتصاد روستایی', '121622', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (233, 'جغرافیا و برنامه ریزی روستایی گرایش برنامه ریزی کالبدی -فضایی', '121623', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (234, 'جغرافیا و برنامه ریزی شهری گرایش برنامه ریزی مسکن و بازآفرینی شهری', '121624', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (235, 'جغرافیاوبرنامه ریزی روستایی-مدیریت توسعه پایدارروستایی', '121628', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (236, 'جغرافیاوبرنامه ریزی روستایی-سازماندهی مناطق عشایری', '121629', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (237, 'جغرافیاوبرنامه ریزی روستایی-اقتصادفضا', '121631', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (238, 'جغرافیاوبرنامه ریزی روستایی-برنامه ریزی کالبدی', '121632', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (239, 'جغرافیاوبرنامه ریزی شهری-آمایش شهری', '121633', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (240, 'جغرافیاوبرنامه ریزی شهری-محیط زیست شهری', '121634', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (241, 'جغرافیاوبرنامه ریزی شهری-برنامه ریزی مسکن', '121635', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (242, 'جغرافیاوبرنامه ریزی شهری-بهسازی ونوسازی', '121636', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (243, 'آب وهوا شناسی(اقلیم شناسی)گرایش آب وهوا شناسی شهری', '121637', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (244, 'آب وهوا شناسی(اقلیم شناسی)گرایش تغییرات آب وهوایی(اقلیمی)', '121638', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (245, 'آب وهوا شناسی(اقلیم شناسی)گرایش آب وهوا شناسی کاربردی', '121639', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (246, 'جغرافیای انسانی (شهری )', '121640', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (247, 'جغرافیای طبیعی (اقلیم شناسی )', '121641', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (248, 'جغرافیای طبیعی (ژئومورفولوژی )', '121642', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (249, 'جغرافیا وبرنامه ریزی شهری', '121643', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (250, 'جغرافیا و برنامه ریزی شهری', '121647', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (251, 'جغرافیاوبرنامه ریزی شهری', '121648', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (252, 'جغرافیای طبیعی (اقلیم شناسی دربرنامه ریزی محیطی)', '121655', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (253, 'ژئومورفولوژی گرایش هیدرو ژئومورفولوژی در برنامه ریزی محیطی', '121656', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (254, 'جغرافیا و برنامه ریزی روستایی', '121664', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (255, 'جغرافیا و برنامه ریزی شهری', '121665', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (256, 'آب و هوا شناسی', '121666', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (257, 'ژئومورفولوژی', '121667', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (258, 'جغرافیا و برنامه ریزی روستایی گرایش برنامه ریزی آمایش کیفیت محیطی مناطق روستایی', '121668', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (259, 'ژئومورفولوژی گرایش ژئومورفولوژی و آمایش محیط', '121669', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (260, 'آب و هواشناسی گرایش سینوپتیک', '121670', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (261, 'آب وهواشناسی گرایش تغییر اقلیم', '121671', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (262, 'آب و هواشناسی گرایش آب و هواشناسی محیطی', '121672', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (263, 'جغرافیای سیاسی', '121673', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (264, 'مخاطرات محیطی', '121674', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (265, 'روانشناسی گرایش روانشناسی عمومی', '121710', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (266, 'روانشناسی اسلامی گرایش روانشناسی مثبت گرا', '121711', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (267, 'روانشناسی بالینی کودک و نوجوان', '121714', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (268, 'روانشناسی شخصیت', '121715', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (269, 'روانشناسی و آموزش کودکان استثنایی(عقب مانده ذهنی)', '121716', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (270, 'مشاوره', '121717', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (271, 'روانشناسی تربیتی', '121718', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (272, 'روانشناسی بالینی', '121719', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (273, 'روانشناسی عمومی', '121720', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (274, 'روان شناسی', '121722', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (275, 'روانشناسی گرایش روانشناسی عمومی', '121723', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (276, 'روانشناسی-سلامت', '121727', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (277, 'روانشناسی', '121728', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (278, 'رو انشناسی', '121729', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (279, 'مدیریت دولتی گرایش مدیریت منابع انسانی', '121808', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (280, 'مدیریت دولتی', '121810', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (281, 'مدیریت فناوری اطلاعات(کسب وکار الکترونیک)', '121811', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (282, 'مدیریت فناوری اطلاعات(مدیریت منابع اطلاعاتی)', '121812', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (283, 'مدیریت فناوری اطلاعات(سیستمهای اطلاعاتی پیشرفته)', '121813', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (284, 'مدیریت فناوری اطلاعات(مدیریت دانش)', '121814', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (285, 'کارآفرینی گرایش کسب و کار جدید', '121815', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (286, 'کارآفرینی گرایش آموزش عالی', '121816', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (287, 'مدیریت کسب و کار (MBA) گرایش استراتژی', '121817', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (288, 'مدیریت کسب و کار (MBA) گرایش بازاریابی', '121818', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (289, 'مدیریت کسب و کار (MBA) گرایش کار آفرینی', '121819', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (290, 'مدیریت بازرگانی', '121820', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (291, 'مدیریت کسب و کار (MBA) گرایش کسب و کار بین المللی', '121821', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (292, 'مدیریت کسب و کار (MBA) گرایش مالی', '121822', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (293, 'مدیریت کسب و کار(MBA) گرایش رفتار سازمانی و منابع انسانی', '121823', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (294, 'مدیریت کسب و کار(MBA) گرایش سیستمهای اطلاعاتی و فناوری اطلاعات', '121824', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (295, 'مدیریت امور شهری', '121825', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (296, 'مدیریت بازرگانی گرایش مدیریت تحول', '121826', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (297, 'مدیریت دولتی گرایش مدیریت نیروی انسانی', '121827', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (298, 'مدیریت بازرگانی گرایش مدیریت بازاریابی', '121828', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (299, 'مدیریت بازرگانی گرایش سیاست گذاری بازرگانی', '121829', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (300, 'مدیریت دولتی -مدیریت منابع انسانی', '121830', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (301, 'مدیریت بازرگانی گرایش رفتار سازمانی و مدیریت منابع انسانی', '121831', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (302, 'جهانگردی', '121832', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (303, 'مدیریت بازرگانی گرایش تجارت الکترونیکی', '121833', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (304, 'مدیریت بازرگانی گرایش مدیریت استراتژیک', '121834', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (305, 'مدیریت بازرگانی گرایش بازرگانی داخلی', '121835', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (306, 'مدیریت بازرگانی گرایش کارآفرینی', '121836', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (307, 'مدیریت دولتی گرایش توسعه منابع انسانی', '121837', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (308, 'مدیریت بازرگانی-مدیریت مالی', '121838', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (309, 'مدیریت بازرگانی (بازرگانی بین المللی)', '121839', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (310, 'مدیریت بازرگانی (بازاریابی)', '121840', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (311, 'مدیریت جهانگردی', '121843', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (312, 'مدیریت بازرگانی (بازاریابی -بازرگانی بین الم', '121844', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (313, 'مدیریت صنعتی', '121845', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (314, 'مدیریت اجرایی', '121846', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (315, 'مدیریتMBA', '121847', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (316, 'مدیریت دولتی-منابع انسانی', '121848', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (317, 'مدیریت بازرگانی', '121849', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (318, 'مدیریت دولتی-تشکیلات وروشها', '121850', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (319, 'مدیریت دولتی-مدیریت تحول', '121851', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (320, 'مدیریت اجرایی (بازاریابی و صادرات)', '121853', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (321, 'مدیریت اجرایی ( استراتژیک )', '121854', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (322, 'مدیریت دولتی-رفتارسازمانی', '121856', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (323, 'مدیریت دولتی- مدیریت مالی دولتی', '121857', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (324, 'مدیریت دولتی -مدیریت سیستمهای اطلاعاتی', '121858', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (325, 'مدیریت منابع انسانی-مدیریت منابع انسانی اسلامی', '121859', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (326, 'مدیریت دولتی گرایش طراحی سازمان های دولتی', '121860', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (327, 'مدیریت دولتی گرایش بودجه و مالیه عمومی', '121861', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (328, 'مدیریت دولتی گرایش خط مشی گذاری عمومی', '121862', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (329, 'مدیریت دولتی گرایش مدیریت پیشرفت و توسعه شهری و روستایی', '121863', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (330, 'مدیریت دولتی گرایش مدیریت رفتار سازمانی', '121864', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (331, 'کارآفرینی گرایش کسب و کار الکترونیکی', '121865', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (332, 'کارآفرینی گرایش فناوری', '121866', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (333, 'کارآفرینی گرایش گردشگری', '121867', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (334, 'کارآفرینی گرایش خدمات کشاورزی', '121868', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (335, 'کارآفرینی گرایش فناوری اطلاعات', '121869', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (336, 'کارآفرینی گرایش سازمانی', '121870', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (337, 'کارآفرینی گرایش بین الملل', '121871', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (338, 'کارآفرینی گرایش بخش عمومی', '121872', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (339, 'کارآفرینی گرایش آموزش و ترویج کارآفرینی', '121873', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (340, 'کارآفرینی گرایش توسعه', '121874', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (341, 'مدیریت کسب و کار گرایش استراتژی', '121875', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (342, 'مدیریت کسب و کار گرایش بازاریابی', '121876', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (343, 'مدیریت کسب و کار گرایش مالی', '121877', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (344, 'مدیریت کسب و کار گرایش سیستم های اطلاعاتی و فناوری اطلاعات', '121878', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (345, 'مدیریت کسب و کار گرایش رفتار سازمانی و منابع انسانی', '121879', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (346, 'مدیریت امور بانکی', '121880', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (347, 'مدیریت جهانگردی گرایش بازاریابی جهانگردی', '121881', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (348, 'مدیریت سازمانهای دولتی گرایش مالی و اقتصادی', '121882', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (349, 'مدیریت امور گمرکی', '121883', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (350, 'مدیریت کسب و کار گرایش عملیات زنجیره تامین', '121884', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (351, 'مدیریت کسب و کار گرایش فناوری', '121885', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (352, 'مدیریت بیمه', '121886', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (353, 'گردشگری', '121887', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (354, 'مدیریت کسب و کار گرایش انرژی', '121888', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (355, 'فلسفه تعلیم وتربیت - تعلیم وتربیت اسلامی', '121909', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (356, 'فلسفه وکلام اسلامی گرایش فلسفه اسلامی', '121910', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (357, 'فلسفه و کلام اسلامی گرایش کلام اسلامی', '121911', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (358, 'فلسفه و کلام اسلامی', '121912', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (359, 'الهیات ومعارف اسلامی-فلسفه وکلام اسلامی', '122006', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (360, 'الهیات ومعارف اسلامی-فقه ومبانی حقوق اسلامی', '122007', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (361, 'علوم ومعارف نهج البلاغه', '122008', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (362, 'علوم قرآن وحدیث', '122009', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (363, 'الهیات (برنامه نه ترم قدیم )', '122010', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (364, 'الهیات و معارف اسلامی گرایش تاریخ و تمدن ملل اسلامی', '122012', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (365, 'نهج البلاغه گرایش اخلاق و تربیت فردی و اجتماعی', '122014', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (366, 'تربیت معلم قرآن کریم', '122015', 7, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (367, 'نهج البلاغه گرایش اجتماعی، سیاسی و حقوق عمومی', '122016', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (368, 'فقه و حقوق خصوصی', '122017', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (369, 'علوم قرآن و حدیث', '122018', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (370, 'ادیان و عرفان', '122019', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (371, 'تاریخ تمدن ملل اسلامی', '122021', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (372, 'فقه و مبانی حقوق اسلامی', '122022', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (373, 'فلسفه و کلام اسلامی', '122023', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (374, 'فلسفه دین', '122024', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (375, 'اخلاق کاربردی', '122025', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (376, 'علوم قرآن و حدیث- مطالعات حدیث', '122026', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (377, 'علوم قرآن و حدیث- مطالعات قرآن', '122027', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (378, 'ادیان و عرفان', '122028', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (379, 'فلسفه وحکمت اسلامی', '122029', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (380, 'الهیات ومعارف اسلامی-فلسفه و کلام اسلامی', '122030', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (381, 'الهیات ومعارف اسلامی-علوم قرآن و حدیث', '122040', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (382, 'نهج البلاغه گرایش اصول دین ومعارف علوی', '122041', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (383, 'اخلاق گرایش فلسفه اخلاق', '122045', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (384, 'اخلاق گرایش اخلاق اسلامی', '122047', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (385, 'الهیات ومعارف اسلامی-فقه و مبانی حقوق اسلامی', '122050', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (386, 'الهیات ومعارف اسلامی گرایش ادیان وعرفان', '122059', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (387, 'الهیات ومعارف اسلامی گرایش تاریخ فرهنگ وتمدن اسلامی', '122060', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (388, 'الهیات ومعارف اسلامی گرایش علوم قرآن وحدیث', '122061', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (389, 'الهیات ومعارف اسلامی گرایش فلسفه وکلام اسلامی', '122062', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (390, 'الهیات و معارف اسلامی گرایش فقه ومبانی حقوق اسلامی', '122063', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (391, 'مدرسی معارف اسلامی -مبانی نظری اسلام', '122065', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (392, 'مدرسی معارف اسلامی-تاریخ وتمدن اسلامی', '122066', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (393, 'مدرسی معارف اسلامی-قرآن و متون اسلامی', '122073', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (394, 'آموزش دینی- عربی', '122074', 7, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (395, 'کلام-فلسفه دین', '122075', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (396, 'اخلاق گرایش اخلاق کاربردی', '122076', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (397, 'علوم اقتصادی (اقتصادنظری )', '122110', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (398, 'علوم اقتصادی', '122111', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (399, 'علوم اقتصادی', '122112', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (400, 'علوم اقتصادی (نظری )', '122113', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (401, 'علوم اقتصادی (اقتصاد سنجی)', '122114', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (402, 'علوم اقتصادی(اقتصاد بین الملل)', '122115', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (403, 'علوم اقتصادی (اقتصاد اسلامی )', '122116', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (404, 'علوم اقتصادی (اقتصاد پولی)', '122118', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (405, 'علوم اقتصادی (اقتصاد بخش عمومی)', '122119', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (406, 'اقتصاد اسلامی', '122122', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (407, 'علوم اقتصادی گرایش اقتصاد نظری', '122123', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (408, 'اقتصاد انرژی', '122124', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (409, 'اقتصاد و تجارت الکترونیک', '122125', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (410, 'علوم ا قتصادی', '122126', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (411, 'علوم اقتصادی گرایش اقتصاداسلامی', '122127', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (412, 'علوم اقتصادی گرایش بانکداری اسلامی', '122128', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (413, 'علوم اقتصادی گرایش اقتصاد انرژی', '122129', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (414, 'علوم اقتصادی گرایش اقتصاد و تجارت الکترونیک', '122130', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (415, 'علوم اقتصادی گرایش برنامه ریزی سیستم های اقتصادی', '122131', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (416, 'علوم اقتصادی گرایش توسعه اقتصادی و برنامه ریزی', '122132', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (417, 'اقتصاد', '122133', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (418, 'جامعه شناسی', '122211', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (419, 'ارتباطات اجتماعی گرایش روزنامه نگاری', '122212', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (420, 'علوم اجتماعی گرایش مطالعات فرهنگی', '122213', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (421, 'برنامه ریزی رفاه اجتماعی', '122214', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (422, 'پژوهشگری اجتماعی', '122215', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (423, 'تعاون و رفاه اجتماعی', '122216', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (424, 'روابط عمومی', '122217', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (425, 'روزنامه نگاری', '122218', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (426, 'مددکاری اجتماعی', '122219', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (427, 'علوم اجتماعی (تعاون ورفاه اجتماعی )', '122220', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (428, 'برنامه ریزی اجتماعی و تعاون', '122222', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (429, 'مطالعات فرهنگی', '122223', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (430, 'جامعه شناسی', '122224', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (431, 'علوم اجتماعی (پژوهشگری علوم اجتماعی )', '122230', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (432, 'روزنامه نگاری', '122241', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (433, 'جمعیت شناسی', '122249', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (434, 'علوم اجتماعی (پژوهشگری )', '122251', 6, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (435, 'علوم اجتماعی (مددکاری اجتماعی)', '122258', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (436, 'علوم اجتماعی (برنامه ریزی اجتماعی تعاون و رفاه)', '122259', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (437, 'علوم ارتباطات اجتماعی (روزنامه نگاری)', '122260', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (438, 'علوم ارتباطات اجتماعی (روابط عمومی)', '122261', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (439, 'حقوق', '122310', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (440, 'حقوق بین الملل', '122312', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (441, 'حقوق دادرسی اداری', '122313', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (442, 'حقوق بین الملل عمومی', '122314', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (443, 'حقوق بین الملل', '122320', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (444, 'حقوق بین الملل', '122330', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (445, 'حقوق جزاوجرم شناسی', '122332', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (446, 'حقوق خصوصی', '122333', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (447, 'حقوق خصوصی', '122335', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (448, 'علم اطلاعات و دانش شناسی', '122410', 6, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (449, 'علم اطلاعات ودانش شناسی', '122411', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (450, 'علم سنجی', '122412', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (451, 'علم اطلاعات و دانش شناسی گرایش مدیریت اطلاعات', '122414', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (452, 'علم اطلاعات و دانش شناسی گرایش مدیریت کتابخانه های دیجیتال', '122419', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (453, 'علم اطلاعات ودانش شناسی', '122420', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (454, 'علوم کتابداری و اطلاع رسانی ( مدیریت فناوری اطلاعات)', '122423', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (455, 'علم اطلاعات و دانش شناسی', '122425', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (456, 'علم اطلاعات ودانش شناسی-مطالعات کتابخانه های عمومی', '122426', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (457, 'زبان وادبیات انگلیسی', '122510', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (458, 'آموزش زبان انگلیسی', '122511', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (459, 'آموزش زبان انگلیسی', '122513', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (460, 'آموزش زبان انگلیسی', '122514', 7, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (461, 'صنایع دستی', '122610', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (462, 'جامعه شناسی', '122710', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (463, 'جامعه شناسی حوزه مطالعات شهری صنعتی', '122713', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (464, 'جامعه شناسی-مسائل اجتماعی ایران', '122715', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (465, 'جامعه شناسی (جامعه شناسی مسائل اجتماعی )', '122716', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (466, 'تاریخ اسلام', '122909', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (467, 'تاریخ', '122910', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (468, 'تاریخ گرایش تاریخ تشیع', '122911', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (469, 'تاریخ (کاردانی )', '122912', 6, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (470, 'تاریخ-تاریخ ایران اسلامی', '122913', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (471, 'تاریخ- تاریخ ایران بعد ازاسلام', '122916', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (472, 'تاریخ-تاریخ اسلام', '122917', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (473, 'تاریخ انقلاب اسلامی', '122918', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (474, 'تاریخ گرایش مطالعات آسیای مرکزی و قفقاز', '122919', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (475, 'تاریخ گرایش تاریخ ایران دوره اسلام', '122920', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (476, 'زبان و ادبیات عربی', '123010', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (477, 'زبان وادبیات عرب', '123011', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (478, 'زبان و ادبیات عربی-ادبیات عربی', '123013', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (479, 'زبان و ادبیات عربی', '123014', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (480, 'علوم سیاسی گرایش اندیشه سیاسی در اسلام', '123110', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (481, 'علوم سیاسی', '123111', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (482, 'علوم سیاسی', '123114', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (483, 'مدیریت دولتی', '123411', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (484, 'مدیریت بازرگانی', '123511', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (485, 'مدیریت صنعتی', '123811', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (486, 'مدیریت جهانگردی', '123911', 8, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (487, 'آموزش محیط زیست', '124010', 10, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (488, 'آموزش محیط زیست', '124011', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (489, 'محیط زیست گرایش آموزش محیط زیست', '124013', 9, 7);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (490, 'مهندسی فناوری اطلاعات-سیستمهای چند رسانه ای', '131010', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (491, 'مهندسی مدیریت اجرایی', '131112', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (492, 'مهندسی مدیریت پروژه', '131212', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (493, 'مهندسی عمران- راه وترابری', '131309', 10, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (494, 'مهندسی عمران - سازه های هیدرولیکی', '131310', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (495, 'مهندسی عمران-راه وترابری', '131311', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (496, 'مهندسی عمران - نقشه برداری', '131312', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (497, 'مهندسی عمران', '131316', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (498, 'مهندسی عمران - سازه', '131317', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (499, 'مهندسی عمران - مهندسی و مدیریت ساخت', '131318', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (500, 'مهندسی عمران-محیط زیست', '131319', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (501, 'مهندسی عمران-خاک وپی', '131320', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (502, 'مهندسی عمران- مهندسی آب و سازه های هیدرولیکی', '131321', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (503, 'مهندسی عمران- ژئوتکنیک', '131322', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (504, 'مهندسی نقشه برداری', '131323', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (505, 'مهندسی صنایع-مدیریت سیستم وبهره وری', '131410', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (506, 'مهندسی صنایع- سیستمهای اقتصادی اجتماعی', '131411', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (507, 'مهندسی صنایع', '131412', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (508, 'مهندسی صنایع- بهینه سازی سیستم ها', '131413', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (509, 'مهندسی صنایع- مدل سازی سیستم های کلان', '131414', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (510, 'آینده پژوهی', '131417', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (511, 'مهندسی صنایع گرایش مدیریت مهندسی', '131418', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (512, 'مهندسی صنایع- سیستم های کلان', '131419', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (513, 'مهندسی صنایع گرایش سیستم های کلان اقتصادی و اجتماعی', '131420', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (514, 'مهندسی مکانیک-تبدیل انرژی', '131508', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (515, 'مهندسی مکانیک-ساخت وتولید', '131509', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (516, 'مهندسی مکانیک گرایش حرارت و سیالات', '131510', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (517, 'مهندسی مکانیک-طراحی کاربردی', '131511', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (518, 'مهندسی خودرو', '131512', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (519, 'مهندسی مکانیک گرایش ساخت و تولید', '131513', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (520, 'مهندسی هوا فضا', '131514', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (521, 'مهندسی مکانیک گرایش مکانیک جامدات', '131515', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (522, 'مهندسی متالورژی ومواد- متالورژی صنعتی', '131516', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (523, 'مهندسی مکانیک', '131517', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (524, 'مهندسی شیمی گرایش صنایع غذایی', '131710', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (525, 'مهندسی شیمی-بیوتکنولوژی', '131711', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (526, 'مهندسی نفت - صنایع نفت', '131712', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (527, 'مهندسی شیمی گرایش صنایع پالایش، پتروشیمی و گاز', '131713', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (528, 'مهندسی پلیمر - صنایع پلیمر', '131714', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (529, 'مهندسی شیمی', '131715', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (530, 'مهندسی پلیمر - علوم و تکنولوژی رنگ', '131716', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (531, 'مهندسی شیمی گرایش طراحی فرآیند', '131717', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (532, 'مهندسی شیمی - محیط زیست', '131719', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (533, 'مهندسی نفت - طراحی فرآیندهای صنایع نفت', '131720', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (534, 'مهندسی شیمی - مدل سازی، شبیه سازی و کنترل', '131721', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (535, 'مهندسی شیمی - پلیمر', '131722', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (536, 'مهندسی شیمی - صنایع غذایی', '131723', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (537, 'مهندسی پلیمر', '131724', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (538, 'مهندسی نفت', '131725', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (539, 'مهندسی پزشکی - گرایش بیومتریال', '131810', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (540, 'مهندسی پزشکی - بالینی', '131811', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (541, 'مهندسی پزشکی - گرایش بیومکانیک', '131812', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (542, 'مهندسی پزشکی', '131813', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (543, 'مهندسی برق - گرایش قدرت', '131910', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (544, 'مهندسی برق - گرایش مهندسی پزشکی (بیوالکتریک)', '131911', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (545, 'مهندسی برق - گرایش کنترل', '131912', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (546, 'مهندسی برق - گرایش مخابرات', '131913', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (547, 'مهندسی برق - گرایش الکترونیک', '131914', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (548, 'مهندسی برق گرایش مدارهای مجتمع الکترونیک', '131915', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (549, 'مهندسی برق گرایش افزاره های میکرو و نانو الکترونیک', '131916', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (550, 'مهندسی برق', '131917', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (551, 'مهندسی برق-الکترونیک', '131918', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (552, 'مهندسی راه آهن - سازه های ریلی', '132010', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (553, 'مهندسی راه آهن - بهره برداری', '132011', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (554, 'مهندسی راه آهن - جریه', '132012', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (555, 'مهندسی راه آهن', '132013', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (556, 'مهندسی مواد-شناسایی وانتخاب مواد مهندسی', '132110', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (557, 'مهندسی مواد و متالورژی', '132111', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (558, 'مهندسی کامپیوتر گرایش نرم افزار', '132210', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (559, 'مهندسی کامپیوتر گرایش معماری سیستم های کامپیوتری', '132211', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (560, 'مهندسی کامپیوتر گرایش رایانش امن', '132212', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (561, 'مهندسی کامپیوتر گرایش فناوری اطلاعات', '132213', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (562, 'مهندسی فناوری اطلاعات گرایش مدیریت سیستمهای اطلاعاتی', '132214', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (563, 'مهندسی کامپیوتر گرایش هوش مصنوعی و رباتیکز', '132216', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (564, 'مهندسی کامپیوتر', '132217', 8, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (565, 'مهندسی فناوری اطلاعات', '132218', 9, 3);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (566, 'مهندسی منابع طبیعی-محیط زیست(ارزیابی وآمایش سرزمین)', '141110', 9, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (567, 'مهندسی کشاورزی-بیوتکنولوژی کشاورزی', '141111', 9, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (568, 'مهندسی کشاورزی -اقتصادکشاورزی', '141112', 9, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (569, 'مهندسی کشاورزی- اقتصاد کشاورزی(مدیریت وتولید کشاورزی)', '141115', 9, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (570, 'مهندسی کشاورزی-علوم دامی(گرایش تغذیه دام)', '141116', 9, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (571, 'مهندسی کشاورزی-بیماری شناسی گیاهی', '141117', 9, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (572, 'مهندسی مکانیزاسیون کشاورزی-انرژی', '141118', 9, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (573, 'علوم و مهندسی صنایع غذایی (کشاورزی)', '141119', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (574, 'مهندسی ماشینهای کشاورزی و مکانیزاسیون', '141120', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (575, 'مهندسی علوم کشاورزی', '141121', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (576, 'مهندسی مدیریت وآبادانی روستاها', '141122', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (577, 'مهندسی آب وخاک', '141123', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (578, 'مهندسی منابع طبیعی -محیط زیست', '141124', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (579, 'مهندسی کشاورزی (علوم دامی )', '141125', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (580, 'مهندسی کشاورزی - اقتصادکشاورزی', '141126', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (581, 'مهندسی تولیدات دامی', '141127', 7, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (582, 'مهندسی کشاورزی-زراعت', '141128', 9, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (583, 'مهندسی کشاورزی-اصلاح نباتات', '141129', 9, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (584, 'مهندسی کشاورزی - ترویج و آموزش کشاورزی گرایش زراعت', '141130', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (585, 'مهندسی منابع طبیعی شیلات(تکثیر و پرورش آبزیان)', '141131', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (586, 'مهندسی کشاورزی - علوم و صنایع غذایی', '141132', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (587, 'مهندسی کشاورزی- زراعت و اصلاح نباتات گرایش زراعت', '141133', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (588, 'مهندسی کشاورزی- ترویج و آموزش کشاورزی', '141134', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (589, 'مهندسی شیلات', '141135', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (590, 'علوم و مهندسی محیط زیست', '141136', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (591, 'مهندسی علوم دامی', '141137', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (592, 'مهندسی زراعت و اصلاح نباتات', '141138', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (593, 'ترویج و آموزش کشاورزی', '141139', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (594, 'بیوتکنولوژی کشاورزی', '141140', 9, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (595, 'علوم و مهندسی شیلات', '141141', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (596, 'مهندسی تولید و ژنتیک گیاهی', '141142', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (597, 'علوم دامی گرایش تغذیه دام', '141143', 9, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (598, 'علوم و مهندسی محیط زیست گرایش ارزیابی و آمایش سرزمین', '141144', 9, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (599, 'ترویج و آموزش کشاورزی پایدار', '141145', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (600, 'علوم دامی', '141146', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (601, 'مهندسی کشاورزی-توسعه روستایی(گرایش توسعه کشاورزی)', '141210', 9, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (602, 'مهندسی توسعه روستایی', '141211', 9, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (603, 'توسعه روستایی', '141212', 9, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (604, 'اقتصاد کشاورزی-سیاست وتوسعه کشاورزی', '141310', 10, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (605, 'مهندسی اقتصاد کشاورزی-سیاست وتوسعه کشاورزی', '141311', 9, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (606, 'مهندسی اقتصادکشاورزی-اقتصادتولیدومدیریت واحدهای کشاورزی', '141312', 9, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (607, 'مهندسی کشاورزی - اقتصاد کشاورزی', '141313', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (608, 'اقتصاد کشاورزی', '141314', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (609, 'اقتصاد کشاورزی گرایش اقتصاد تولید و مدیریت واحدهای کشاورزی', '141315', 9, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (610, 'اقتصاد کشاورزی گرایش سیاست و توسعه کشاورزی', '141316', 9, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (611, 'مهندسی کشاورزی-آب', '141410', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (612, 'علوم و مهندسی آب', '141411', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (613, 'مهندسی کشاورزی-مکانیزاسیون کشاورزی', '141510', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (614, 'مهندسی مکانیزاسیون کشاورزی', '141511', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (615, 'مهندسی مکانیزاسیون کشاورزی خوشه انرژی', '141534', 8, 2);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (616, 'مهندسی فناوری اطلاعات', '151112', 8, 4);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (617, 'مهندسی کامپیوتر- نرم افزار', '151113', 8, 4);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (618, 'علوم کامپیوتر', '151114', 8, 4);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (619, 'مهندسی کامپیوتر(سخت افزار)', '151115', 8, 4);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (620, 'مهندسی رباتیک', '151116', 8, 4);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (621, 'پژوهش هنر', '171212', 9, 5);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (622, 'مدیریت رسانه', '171213', 9, 5);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (623, 'هنر اسلامی (گرایش نگارگری)', '171214', 8, 5);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (624, 'علم اطلاعات و دانش شناسی', '171215', 8, 5);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (625, 'طراحی پارچه', '171216', 8, 5);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (626, 'فرش', '181010', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (627, 'کتابت و نگارگری', '181011', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (628, 'هنر اسلامی (گرایش سفال)', '181012', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (629, 'هنر اسلامی (گرایش هنر و صنایع فلز)', '181013', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (630, 'هنر اسلامی (گرایش هنر و صنایع چوب)', '181014', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (631, 'هنر اسلامی (گرایش شیشه)', '181015', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (632, 'هنر اسلامی ( گرایش نگارگری)', '181016', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (633, 'هنرهای صناعی (گرایش آبگینه)', '181017', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (634, 'هنرهای صناعی (گرایش سفال)', '181018', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (635, 'هنرهای صناعی (گرایش فلز)', '181019', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (636, 'هنرهای صناعی (گرایش کاشی)', '181020', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (637, 'هنرهای صناعی (گرایش منبت و معرق)', '181021', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (638, 'هنرهای صناعی (گرایش نساجی سنتی)', '181022', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (639, 'فرش (گرایش طراحی فرش )', '181023', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (640, 'فرش ( گرایش بافت و مرمت فرش )', '181024', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (641, 'کتابت و نگارگری ( گرایش خوشنویسی )', '181025', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (642, 'کتابت و نگارگری ( گرایش طراحی سنتی و تذهیب)', '181026', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (643, 'کتابت و نگارگری ( گرایش نگارگری )', '181027', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (644, 'کتابت و نگارگری ( گرایش خیالی نگاری )', '181028', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (645, 'طراحی پارچه و لباس (گرایش طراحی چاپ پارچه)', '181029', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (646, 'صنایع دستی', '181030', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (647, 'طراحی پارچه', '181031', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (648, 'هنر اسلامی', '181032', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (649, 'هنرهای صناعی', '181033', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (650, 'ارتباط تصویری (گرایش ارتباط تصویری)', '181210', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (651, 'عکاسی', '181211', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (652, 'نقاشی ( گرایش نقاشی عمومی )', '181212', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (653, 'نقاشی', '181213', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (654, 'ارتباط تصویری', '181214', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (655, 'مهندسی شهرسازی', '181310', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (656, 'طراحی شهری', '181311', 9, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (657, 'مهندسی معماری', '181410', 8, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (658, 'مهندسی معماری', '181410', 9, 6);
INSERT INTO ostad_zanis.dbo.Fields (Id, Name, Code, GradeId, CollegeId) VALUES (659, 'مرمت بناهای تاریخی', '181510', 8, 6);